export const FETCH_MOVIES_NOW = 'FETCH_MOVIES_NOW';
export const FETCH_MOVIES_YEAR = 'FETCH_MOVIES_YEAR';
export const FETCH_MOVIES_HIGHEST_RATED = 'FETCH_MOVIES_HIGHEST_RATED';
export const FETCH_MOVIES_MOST_POPULAR = 'FETCH_MOVIES_MOST_POPULAR';
export const FETCH_MOVIES_MOST_POPULAR_KIDS = 'FETCH_MOVIES_MOST_POPULAR_KIDS';

export const MOVIE_CLICKED = 'MOVIE_CLICKED';
export const MOVIE_CLOSED = 'MOVIE_CLOSED';